name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: BeemEnergyAddon/go.mod

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: BeemEnergyAddon/go.mod

      - name: Install KO
        uses: ko-build/setup-ko@v0.9
        env:
          KO_DOCKER_REPO: ghcr.io/funkolab
      
      - name: Build Container
        run: ko build -B